### ISSUE TITLE
Add rasterio to environment.yml

### ISSUE THREAD

**Issue by JeffWalton-PSC** [martibosch/detectree-examples#1]
Add rasterio to environment.yml
- notebook examples require rasterio package

**Comment by JeffWalton-PSC** [comment]
I now see that rasterio is in the detectree requirements.txt file.  So I'm not sure why the notebook background.ipynb generated an error for a missing module. Perhaps just a mistake on my part?

**Comment by martibosch** [comment]
it's strange that such an error is raised because rasterio should be installed as a dependency of the detectree package (which is explicitly listed in the environment.yml).

In any case, I have added rasterio and some other dependencies to the environment.yml file in [7533b0](https://github.com/martibosch/detectree-example/commit/7533b0db51ba6f3a4e7f1d9ac9dfdd3fb456babf).
